"use client";

import { useState } from "react";
import { Check, Download } from "lucide-react";

import { Spinner } from "@/components/ui/button";
import { cn } from "@/lib/cn";
import { EXPORT_FORMATS, type ExportFormat } from "@/lib/types";

/**
 * Export controls.
 *
 * Two deliberate choices:
 *  - The row filter (all / flagged only) is part of the export, because the
 *    most common real workflow is "just give me the broken rows to fix".
 *  - The download is a real navigation, not a fetch + blob. That keeps the
 *    browser's own download UI (progress, resume, "open in Excel") working
 *    instead of reimplementing it badly.
 */
export function ExportBar({
  statementId,
  rowCount,
  flaggedCount,
  disabled = false,
}: {
  statementId: string;
  rowCount: number;
  flaggedCount: number;
  disabled?: boolean;
}) {
  const [format, setFormat] = useState<ExportFormat>("xlsx");
  const [onlyFlagged, setOnlyFlagged] = useState(false);
  const [pending, setPending] = useState(false);
  const [done, setDone] = useState(false);

  const active = EXPORT_FORMATS.find((f) => f.id === format)!;
  const rows = onlyFlagged ? flaggedCount : rowCount;
  const empty = rows === 0;

  const params = new URLSearchParams({ format });
  if (onlyFlagged) params.set("onlyFlagged", "1");
  const href = `/api/statements/${statementId}/export?${params.toString()}`;

  return (
    <div className="panel p-4 sm:p-5">
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <h2 className="text-sm font-semibold text-fg">Export</h2>
        <p className="text-xs text-fg-subtle">Files are generated by the parsing worker</p>
      </div>

      <div
        role="radiogroup"
        aria-label="Export format"
        className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3"
      >
        {EXPORT_FORMATS.map((f) => (
          <button
            key={f.id}
            type="button"
            role="radio"
            aria-checked={format === f.id}
            onClick={() => setFormat(f.id)}
            className={cn(
              "rounded-lg border p-3 text-left transition-colors",
              format === f.id
                ? "border-accent-500/50 bg-accent-500/10"
                : "border-ink-600 hover:border-ink-500 hover:bg-ink-800/60",
            )}
          >
            <span className="flex items-center justify-between gap-2">
              <span className="text-sm font-medium text-fg">{f.label}</span>
              <span className="rounded border border-ink-600 bg-ink-900 px-1.5 py-0.5 font-mono text-[10px] uppercase text-fg-subtle">
                .{f.extension}
              </span>
            </span>
            <span className="mt-1 block text-xs leading-relaxed text-fg-muted">
              {f.description}
            </span>
          </button>
        ))}
      </div>

      <label className="mt-4 flex cursor-pointer items-start gap-3 rounded-lg border border-ink-700 bg-ink-900/50 p-3">
        <input
          type="checkbox"
          checked={onlyFlagged}
          onChange={(e) => setOnlyFlagged(e.target.checked)}
          disabled={flaggedCount === 0}
          className="mt-0.5 size-4 accent-[var(--color-accent-500)]"
        />
        <span className="text-sm">
          <span className="block font-medium text-fg">
            Only export rows that need attention
          </span>
          <span className="mt-0.5 block text-xs text-fg-muted">
            {flaggedCount === 0
              ? "Nothing is flagged on this statement."
              : `${flaggedCount} of ${rowCount} rows would be exported — useful for fixing a mismatch.`}
          </span>
        </span>
      </label>

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <a
          href={disabled || empty ? undefined : href}
          onClick={() => {
            if (disabled || empty) return;
            setPending(true);
            setDone(true);
            window.setTimeout(() => setPending(false), 1200);
          }}
          aria-disabled={disabled || empty}
          className={cn(
            "inline-flex h-10 items-center gap-2 rounded-lg px-4 text-sm font-medium transition-colors",
            disabled || empty
              ? "pointer-events-none bg-ink-700 text-fg-subtle"
              : "bg-accent-500 text-white hover:bg-accent-400",
          )}
        >
          {pending ? (
            <Spinner className="size-4" label="Preparing download" />
          ) : done ? (
            <Check className="size-4" aria-hidden="true" />
          ) : (
            <Download className="size-4" aria-hidden="true" />
          )}
          {pending ? "Preparing…" : done ? "Download again" : `Download ${active.label}`}
        </a>
        <p className="text-xs text-fg-muted">
          <span className="tabular font-medium text-fg">{rows}</span> rows ·{" "}
          {active.audience}
        </p>
      </div>
    </div>
  );
}
